# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: This is Solid State
description: > # this means to ignore newlines until "baseurl:"
  Another free + fully responsive site template by HTML5 UP
postsTitle: Vitae phasellus
postsDescription: Cras mattis ante fermentum, malesuada neque vitae, eleifend erat.
                  Phasellus non pulvinar erat. Fusce tincidunt, nisl eget mattis egestas,
                  purus ipsum consequat orci, sit amet lobortis lorem lacus in tellus.
                  Sed ac elementum arcu. Quisque placerat auctor laoreet.
contactTitle: Get in touch
contactDescription: Cras mattis ante fermentum, malesuada neque vitae, eleifend erat.
                    Phasellus non pulvinar erat. Fusce tincidunt, nisl eget mattis egestas,
                    purus ipsum consequat orci, sit amet lobortis lorem lacus in tellus.
                    Sed ac elementum arcu. Quisque placerat auctor laoreet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
copyright: Copyright Owner
# Contact info
email: youremail@yourdomain.com
twitter: joe
facebook: joe
instagram: joe
youtube: joe
mailingAddress: Untitled Inc<br />1234 Somewhere Road Suite no. 2894<br />Nashville, TN 00000-0000
phone: 012-345-6789
# Build settings
markdown: kramdown